name: fintech_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.1
  pinput: ^5.0.1
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.0
  shared_preferences: ^2.3.2  
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_svg: ^2.0.17
  easy_localization: ^3.0.7+1
  bloc: ^8.1.4
  flutter_secure_storage: ^9.2.4
  json_serializable: ^6.8.0
  build_runner: ^2.3.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.2.0
  freezed: ^2.5.2
  retrofit: ^4.4.1
  retrofit_generator: 
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.5
  loading_animation_widget: ^1.3.0
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  flutter_slidable: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Light.ttf
        weight: 300
      - asset: assets/fonts/Lato-Regular.ttf
        weight: 400
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/Lato-Black.ttf
        weight: 800
      - asset: assets/fonts/Lato-BoldItalic.ttf
        weight: 900